In [57]:
#Defining Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import requests
import gmaps
import os

# Import API key
from test import g_key

In [58]:
#Importing GEO ID's
summ_geo_info = "data/GeoIDs - City.csv"
summ_geo_info_df = pd.read_csv(summ_geo_info)
summ_geo_info_df.head()

,cityid,cityname,stateabbrev,statename,statefips,lat,lon,city_pop2019
0,1,Los Angeles,CA,California,6,34.05,-118.24,10039107
1,2,New York City,NY,New York,36,40.71,-74.01,8336817
2,3,Chicago,IL,Illinois,17,41.88,-87.63,5150233
3,4,Houston,TX,Texas,48,29.76,-95.37,4713325
4,5,Phoenix,AZ,Arizona,4,33.45,-112.07,4485414

In [59]:
#Dropping un-need columns
geo_dropped = summ_geo_info_df.drop(columns=['statename', 'statefips'])
geo_dropped.set_index("cityid")

                cityname stateabbrev    lat     lon  city_pop2019
cityid
1            Los Angeles          CA  34.05 -118.24      10039107
2          New York City          NY  40.71  -74.01       8336817
3                Chicago          IL  41.88  -87.63       5150233
4                Houston          TX  29.76  -95.37       4713325
5                Phoenix          AZ  33.45 -112.07       4485414
6              San Diego          CA  32.72 -117.16       3338330
7                 Dallas          TX  32.78  -96.80       2635516
8              Las Vegas          NV  36.17 -115.14       2266715
9                Seattle          WA  47.61 -122.33       2252782
10            Fort Worth          TX  32.76  -97.33       2102515
11           San Antonio          TX  29.42  -98.49       2003554
12              San Jose          CA  37.34 -121.89       1927852
13               Detroit          MI  42.33  -83.05       1749343
14          Philadelphia          PA  39.95  -75.17       1584064
15              Columbus          OH  39.96  -83.00       1316756
16                Austin          TX  30.27  -97.74       1273954
17             Charlotte          NC  35.23  -80.84       1110356
18          Indianapolis          IN  39.77  -86.16        964582
19          Jacksonville          FL  30.33  -81.66        957755
20               Memphis          TN  35.15  -90.05        937166
21         San Francisco          CA  37.77 -122.42        881549
22               El Paso          TX  31.78 -106.44        839238
23             Baltimore          MD  39.29  -76.61        593490
24              Portland          OR  45.52 -122.68        812855
25                Boston          MA  42.36  -71.06        803907
26         Oklahoma City          OK  35.47  -97.52        797434
27            Louisville          KY  38.25  -85.76        766757
28                Denver          CO  39.74 -104.99        727211
29            Washington          DC  38.91  -77.04        705749
30             Nashville          TN  36.16  -86.78        694144
31             Milwaukee          WI  43.04  -87.91        945726
32           Albuquerque          NM  35.09 -106.61        679121
33                Tucson          AZ  32.22 -110.93       1047279
34                Fresno          CA  36.75 -119.77        999101
35            Sacramento          CA  38.58 -121.49       1552058
36               Atlanta          GA  33.75  -84.39       1063937
37           Kansas City          MO  39.10  -94.58        703011
38                 Miami          FL  25.76  -80.19       2716940
39               Raleigh          NC  35.78  -78.64       1111761
40                 Omaha          NE  41.25  -96.00        571327
41               Oakland          CA  37.80 -122.27       1671329
42           Minneapolis          MN  44.98  -93.27       1265843
43                 Tampa          FL  27.95  -82.46       1471968
44           New Orleans          LA  29.95  -90.07        390144
45               Wichita          KS  37.69  -97.34        516042
46             Cleveland          OH  41.50  -81.69       1235072
47           Bakersfield          CA  35.37 -119.02        900202
48              Honolulu          HI  21.31 -157.86        974563
49                 Boise          ID  43.62 -116.20        481587
50        Salt Lake City          UT  40.76 -111.89       1160437
51        Virginia Beach          VA  36.85  -75.98        449974
52      Colorado Springs          CO  38.83 -104.82        720403
53                 Tulsa          OK  36.15  -95.99        651552

In [60]:
#Importing Womply
summ_womply_info = "data/Womply - City - Daily.csv"
summ_womply_info_df = pd.read_csv(summ_womply_info)
summ_womply_info_df.head()

,year,month,day,cityid,merchants_all,merchants_ss40,merchants_ss60,merchants_ss65,merchants_ss70,revenue_all,revenue_ss40,revenue_ss60,revenue_ss65,revenue_ss70
0,2020,1,10,1,-0.00549,-0.00228,-.00958,-0.01320,0.000077,-0.01250,-0.02480,.0061,-0.0124,-0.01370
1,2020,1,10,2,0.00446,0.00902,-.0249,-0.01630,0.007980,0.00914,-0.00202,.0687,-0.0464,0.03070
2,2020,1,10,3,-0.02340,-0.02080,-.0576,-0.04550,-0.014500,-0.08430,-0.16600,-.0849,-0.0404,-0.04590
3,2020,1,10,4,0.00703,0.01570,.0184,0.00374,0.003980,-0.05660,-0.08300,-.0627,-0.0461,-0.00946
4,2020,1,10,5,0.00891,0.02560,-.0013,0.01110,0.005610,-0.01100,-0.01070,-.0252,-0.0288,0.00742

In [61]:
len(summ_womply_info_df)

21646

In [62]:
#Dropping un-needed columns
womply_dropped = summ_womply_info_df.drop(columns=['merchants_ss40', 'merchants_ss60',
                                 'merchants_ss65', 'merchants_ss70',
                                 'revenue_all','revenue_ss40',
                                  'revenue_ss60','revenue_ss65',
                                 'revenue_ss70'])
womply_dropped

       year  month  day  cityid  merchants_all
0      2020      1   10       1       -0.00549
1      2020      1   10       2        0.00446
2      2020      1   10       3       -0.02340
3      2020      1   10       4        0.00703
4      2020      1   10       5        0.00891
...     ...    ...  ...     ...            ...
21641  2021      2   22      48       -0.28200
21642  2021      2   22      50       -0.24700
21643  2021      2   22      51       -0.35900
21644  2021      2   22      52       -0.29100
21645  2021      2   22      53       -0.39500

[21646 rows x 5 columns]

In [63]:
#Merging geo and womply df's
merge_df = pd.merge(geo_dropped, womply_dropped, on="cityid")
merge_df

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all
0,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,10,-0.00549
1,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,11,-0.00538
2,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,12,-0.00837
3,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,13,-0.01200
4,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,14,-0.00997
...,...,...,...,...,...,...,...,...,...,...
21641,53,Tulsa,OK,36.15,-95.99,651552,2021,2,18,-0.44200
21642,53,Tulsa,OK,36.15,-95.99,651552,2021,2,19,-0.44000
21643,53,Tulsa,OK,36.15,-95.99,651552,2021,2,20,-0.42900
21644,53,Tulsa,OK,36.15,-95.99,651552,2021,2,21,-0.41000
21645,53,Tulsa,OK,36.15,-95.99,651552,2021,2,22,-0.39500

In [64]:
#finding the info only on the 22nd of the month
monthly_ = merge_df['day'] == 22
monthly_merge_df = merge_df[monthly_]
monthly_merge_df

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all
12,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.0147
43,1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.0120
72,1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.2750
103,1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.3990
133,1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.3170
...,...,...,...,...,...,...,...,...,...,...
21522,53,Tulsa,OK,36.15,-95.99,651552,2020,10,22,-0.2530
21553,53,Tulsa,OK,36.15,-95.99,651552,2020,11,22,-0.2750
21583,53,Tulsa,OK,36.15,-95.99,651552,2020,12,22,-0.2430
21614,53,Tulsa,OK,36.15,-95.99,651552,2021,1,22,-0.2930
21645,53,Tulsa,OK,36.15,-95.99,651552,2021,2,22,-0.3950

In [65]:
#merging by cityid
month_merge_df = monthly_merge_df.set_index("cityid")
month_merge_df

,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all
cityid,,,,,,,,,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.0147
1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.0120
1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.2750
1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.3990
1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.3170
...,...,...,...,...,...,...,...,...,...
53,Tulsa,OK,36.15,-95.99,651552,2020,10,22,-0.2530
53,Tulsa,OK,36.15,-95.99,651552,2020,11,22,-0.2750
53,Tulsa,OK,36.15,-95.99,651552,2020,12,22,-0.2430
53,Tulsa,OK,36.15,-95.99,651552,2021,1,22,-0.2930
53,Tulsa,OK,36.15,-95.99,651552,2021,2,22,-0.3950

In [66]:
#adding column to find difference
month_merge_df['Merchants Difference'] = ""
month_merge_df.head(50)

,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all,Merchants Difference
cityid,,,,,,,,,,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.014700,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.012000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.275000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.399000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.317000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,6,22,-0.265000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,7,22,-0.296000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,8,22,-0.313000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,9,22,-0.294000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,10,22,-0.261000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,11,22,-0.256000,
1,Los Angeles,CA,34.05,-118.24,10039107,2020,12,22,-0.324000,
1,Los Angeles,CA,34.05,-118.24,10039107,2021,1,22,-0.362000,
1,Los Angeles,CA,34.05,-118.24,10039107,2021,2,22,-0.333000,
2,New York City,NY,40.71,-74.01,8336817,2020,1,22,0.002910,
2,New York City,NY,40.71,-74.01,8336817,2020,2,22,-0.003000,
2,New York City,NY,40.71,-74.01,8336817,2020,3,22,-0.269000,
2,New York City,NY,40.71,-74.01,8336817,2020,4,22,-0.492000,
2,New York City,NY,40.71,-74.01,8336817,2020,5,22,-0.390000,
2,New York City,NY,40.71,-74.01,8336817,2020,6,22,-0.348000,
2,New York City,NY,40.71,-74.01,8336817,2020,7,22,-0.289000,
2,New York City,NY,40.71,-74.01,8336817,2020,8,22,-0.287000,
2,New York City,NY,40.71,-74.01,8336817,2020,9,22,-0.297000,
2,New York City,NY,40.71,-74.01,8336817,2020,10,22,-0.273000,
2,New York City,NY,40.71,-74.01,8336817,2020,11,22,-0.292000,
2,New York City,NY,40.71,-74.01,8336817,2020,12,22,-0.344000,
2,New York City,NY,40.71,-74.01,8336817,2021,1,22,-0.399000,
2,New York City,NY,40.71,-74.01,8336817,2021,2,22,-0.420000,
3,Chicago,IL,41.88,-87.63,5150233,2020,1,22,-0.024200,
3,Chicago,IL,41.88,-87.63,5150233,2020,2,22,-0.050700,
3,Chicago,IL,41.88,-87.63,5150233,2020,3,22,-0.280000,
3,Chicago,IL,41.88,-87.63,5150233,2020,4,22,-0.406000,
3,Chicago,IL,41.88,-87.63,5150233,2020,5,22,-0.349000,
3,Chicago,IL,41.88,-87.63,5150233,2020,6,22,-0.306000,
3,Chicago,IL,41.88,-87.63,5150233,2020,7,22,-0.294000,
3,Chicago,IL,41.88,-87.63,5150233,2020,8,22,-0.310000,
3,Chicago,IL,41.88,-87.63,5150233,2020,9,22,-0.319000,
3,Chicago,IL,41.88,-87.63,5150233,2020,10,22,-0.306000,
3,Chicago,IL,41.88,-87.63,5150233,2020,11,22,-0.351000,
3,Chicago,IL,41.88,-87.63,5150233,2020,12,22,-0.340000,
3,Chicago,IL,41.88,-87.63,5150233,2021,1,22,-0.357000,
3,Chicago,IL,41.88,-87.63,5150233,2021,2,22,-0.396000,
4,Houston,TX,29.76,-95.37,4713325,2020,1,22,0.002650,
4,Houston,TX,29.76,-95.37,4713325,2020,2,22,0.000262,
4,Houston,TX,29.76,-95.37,4713325,2020,3,22,-0.172000,
4,Houston,TX,29.76,-95.37,4713325,2020,4,22,-0.326000,
4,Houston,TX,29.76,-95.37,4713325,2020,5,22,-0.166000,
4,Houston,TX,29.76,-95.37,4713325,2020,6,22,-0.275000,
4,Houston,TX,29.76,-95.37,4713325,2020,7,22,-0.320000,
4,Houston,TX,29.76,-95.37,4713325,2020,8,22,-0.374000,

In [67]:
month_merge_df_reset = month_merge_df.reset_index(drop=False)
month_merge_df_reset

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all,Merchants Difference
0,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.0147,
1,1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.0120,
2,1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.2750,
3,1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.3990,
4,1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.3170,
...,...,...,...,...,...,...,...,...,...,...,...
733,53,Tulsa,OK,36.15,-95.99,651552,2020,10,22,-0.2530,
734,53,Tulsa,OK,36.15,-95.99,651552,2020,11,22,-0.2750,
735,53,Tulsa,OK,36.15,-95.99,651552,2020,12,22,-0.2430,
736,53,Tulsa,OK,36.15,-95.99,651552,2021,1,22,-0.2930,
737,53,Tulsa,OK,36.15,-95.99,651552,2021,2,22,-0.3950,

In [68]:
for city in month_merge_df_reset["cityname"].unique():
    month_merge_df_reset["Merchants Difference"][month_merge_df_reset["cityname"]==city] = month_merge_df_reset["merchants_all"][month_merge_df_reset["cityname"]==city].diff().tolist()
month_merge_df_reset.head(40)

<ipython-input-68-a5d5d9a93a9f>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  month_merge_df_reset["Merchants Difference"][month_merge_df_reset["cityname"]==city] = month_merge_df_reset["merchants_all"][month_merge_df_reset["cityname"]==city].diff().tolist()

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all,Merchants Difference
0,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.01470,NaN
1,1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.01200,-0.0267
2,1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.27500,-0.263
3,1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.39900,-0.124
4,1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.31700,0.082
5,1,Los Angeles,CA,34.05,-118.24,10039107,2020,6,22,-0.26500,0.052
6,1,Los Angeles,CA,34.05,-118.24,10039107,2020,7,22,-0.29600,-0.031
7,1,Los Angeles,CA,34.05,-118.24,10039107,2020,8,22,-0.31300,-0.017
8,1,Los Angeles,CA,34.05,-118.24,10039107,2020,9,22,-0.29400,0.019
9,1,Los Angeles,CA,34.05,-118.24,10039107,2020,10,22,-0.26100,0.033
10,1,Los Angeles,CA,34.05,-118.24,10039107,2020,11,22,-0.25600,0.005
11,1,Los Angeles,CA,34.05,-118.24,10039107,2020,12,22,-0.32400,-0.068
12,1,Los Angeles,CA,34.05,-118.24,10039107,2021,1,22,-0.36200,-0.038
13,1,Los Angeles,CA,34.05,-118.24,10039107,2021,2,22,-0.33300,0.029
14,2,New York City,NY,40.71,-74.01,8336817,2020,1,22,0.00291,NaN
15,2,New York City,NY,40.71,-74.01,8336817,2020,2,22,-0.00300,-0.00591
16,2,New York City,NY,40.71,-74.01,8336817,2020,3,22,-0.26900,-0.266
17,2,New York City,NY,40.71,-74.01,8336817,2020,4,22,-0.49200,-0.223
18,2,New York City,NY,40.71,-74.01,8336817,2020,5,22,-0.39000,0.102
19,2,New York City,NY,40.71,-74.01,8336817,2020,6,22,-0.34800,0.042
20,2,New York City,NY,40.71,-74.01,8336817,2020,7,22,-0.28900,0.059
21,2,New York City,NY,40.71,-74.01,8336817,2020,8,22,-0.28700,0.002
22,2,New York City,NY,40.71,-74.01,8336817,2020,9,22,-0.29700,-0.01
23,2,New York City,NY,40.71,-74.01,8336817,2020,10,22,-0.27300,0.024
24,2,New York City,NY,40.71,-74.01,8336817,2020,11,22,-0.29200,-0.019
25,2,New York City,NY,40.71,-74.01,8336817,2020,12,22,-0.34400,-0.052
26,2,New York City,NY,40.71,-74.01,8336817,2021,1,22,-0.39900,-0.055
27,2,New York City,NY,40.71,-74.01,8336817,2021,2,22,-0.42000,-0.021
28,3,Chicago,IL,41.88,-87.63,5150233,2020,1,22,-0.02420,NaN
29,3,Chicago,IL,41.88,-87.63,5150233,2020,2,22,-0.05070,-0.0265
30,3,Chicago,IL,41.88,-87.63,5150233,2020,3,22,-0.28000,-0.2293
31,3,Chicago,IL,41.88,-87.63,5150233,2020,4,22,-0.40600,-0.126
32,3,Chicago,IL,41.88,-87.63,5150233,2020,5,22,-0.34900,0.057
33,3,Chicago,IL,41.88,-87.63,5150233,2020,6,22,-0.30600,0.043
34,3,Chicago,IL,41.88,-87.63,5150233,2020,7,22,-0.29400,0.012
35,3,Chicago,IL,41.88,-87.63,5150233,2020,8,22,-0.31000,-0.016
36,3,Chicago,IL,41.88,-87.63,5150233,2020,9,22,-0.31900,-0.009
37,3,Chicago,IL,41.88,-87.63,5150233,2020,10,22,-0.30600,0.013
38,3,Chicago,IL,41.88,-87.63,5150233,2020,11,22,-0.35100,-0.045
39,3,Chicago,IL,41.88,-87.63,5150233,2020,12,22,-0.34000,0.011

In [69]:
#find the month to month difference
#month_merge_df_reset= month_merge_df_reset.drop(month_merge_df_reset["Merchants Difference"]=="NaN")
#month_merge_df_reset["Merchants Difference"].fillna(0)
month_merge_df_reset["Difference plus 1"] = ((month_merge_df_reset["Merchants Difference"] + 1)*100)
month_merge_df_reset.head(40)

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all,Merchants Difference,Difference plus 1
0,1,Los Angeles,CA,34.05,-118.24,10039107,2020,1,22,0.01470,NaN,NaN
1,1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.01200,-0.0267,97.33
2,1,Los Angeles,CA,34.05,-118.24,10039107,2020,3,22,-0.27500,-0.263,73.7
3,1,Los Angeles,CA,34.05,-118.24,10039107,2020,4,22,-0.39900,-0.124,87.6
4,1,Los Angeles,CA,34.05,-118.24,10039107,2020,5,22,-0.31700,0.082,108.2
5,1,Los Angeles,CA,34.05,-118.24,10039107,2020,6,22,-0.26500,0.052,105.2
6,1,Los Angeles,CA,34.05,-118.24,10039107,2020,7,22,-0.29600,-0.031,96.9
7,1,Los Angeles,CA,34.05,-118.24,10039107,2020,8,22,-0.31300,-0.017,98.3
8,1,Los Angeles,CA,34.05,-118.24,10039107,2020,9,22,-0.29400,0.019,101.9
9,1,Los Angeles,CA,34.05,-118.24,10039107,2020,10,22,-0.26100,0.033,103.3
10,1,Los Angeles,CA,34.05,-118.24,10039107,2020,11,22,-0.25600,0.005,100.5
11,1,Los Angeles,CA,34.05,-118.24,10039107,2020,12,22,-0.32400,-0.068,93.2
12,1,Los Angeles,CA,34.05,-118.24,10039107,2021,1,22,-0.36200,-0.038,96.2
13,1,Los Angeles,CA,34.05,-118.24,10039107,2021,2,22,-0.33300,0.029,102.9
14,2,New York City,NY,40.71,-74.01,8336817,2020,1,22,0.00291,NaN,NaN
15,2,New York City,NY,40.71,-74.01,8336817,2020,2,22,-0.00300,-0.00591,99.409
16,2,New York City,NY,40.71,-74.01,8336817,2020,3,22,-0.26900,-0.266,73.4
17,2,New York City,NY,40.71,-74.01,8336817,2020,4,22,-0.49200,-0.223,77.7
18,2,New York City,NY,40.71,-74.01,8336817,2020,5,22,-0.39000,0.102,110.2
19,2,New York City,NY,40.71,-74.01,8336817,2020,6,22,-0.34800,0.042,104.2
20,2,New York City,NY,40.71,-74.01,8336817,2020,7,22,-0.28900,0.059,105.9
21,2,New York City,NY,40.71,-74.01,8336817,2020,8,22,-0.28700,0.002,100.2
22,2,New York City,NY,40.71,-74.01,8336817,2020,9,22,-0.29700,-0.01,99
23,2,New York City,NY,40.71,-74.01,8336817,2020,10,22,-0.27300,0.024,102.4
24,2,New York City,NY,40.71,-74.01,8336817,2020,11,22,-0.29200,-0.019,98.1
25,2,New York City,NY,40.71,-74.01,8336817,2020,12,22,-0.34400,-0.052,94.8
26,2,New York City,NY,40.71,-74.01,8336817,2021,1,22,-0.39900,-0.055,94.5
27,2,New York City,NY,40.71,-74.01,8336817,2021,2,22,-0.42000,-0.021,97.9
28,3,Chicago,IL,41.88,-87.63,5150233,2020,1,22,-0.02420,NaN,NaN
29,3,Chicago,IL,41.88,-87.63,5150233,2020,2,22,-0.05070,-0.0265,97.35
30,3,Chicago,IL,41.88,-87.63,5150233,2020,3,22,-0.28000,-0.2293,77.07
31,3,Chicago,IL,41.88,-87.63,5150233,2020,4,22,-0.40600,-0.126,87.4
32,3,Chicago,IL,41.88,-87.63,5150233,2020,5,22,-0.34900,0.057,105.7
33,3,Chicago,IL,41.88,-87.63,5150233,2020,6,22,-0.30600,0.043,104.3
34,3,Chicago,IL,41.88,-87.63,5150233,2020,7,22,-0.29400,0.012,101.2
35,3,Chicago,IL,41.88,-87.63,5150233,2020,8,22,-0.31000,-0.016,98.4
36,3,Chicago,IL,41.88,-87.63,5150233,2020,9,22,-0.31900,-0.009,99.1
37,3,Chicago,IL,41.88,-87.63,5150233,2020,10,22,-0.30600,0.013,101.3
38,3,Chicago,IL,41.88,-87.63,5150233,2020,11,22,-0.35100,-0.045,95.5
39,3,Chicago,IL,41.88,-87.63,5150233,2020,12,22,-0.34000,0.011,101.1

In [70]:
diff_max= month_merge_df_reset["Difference plus 1"].max()

In [71]:
gmaps.configure(api_key=g_key)

In [72]:
heat_1_df = month_merge_df_reset[(month_merge_df_reset["month"]==2)&(month_merge_df_reset["year"]==2020)]
heat_1_df

,cityid,cityname,stateabbrev,lat,lon,city_pop2019,year,month,day,merchants_all,Merchants Difference,Difference plus 1
1,1,Los Angeles,CA,34.05,-118.24,10039107,2020,2,22,-0.012000,-0.0267,97.33
15,2,New York City,NY,40.71,-74.01,8336817,2020,2,22,-0.003000,-0.00591,99.409
29,3,Chicago,IL,41.88,-87.63,5150233,2020,2,22,-0.050700,-0.0265,97.35
43,4,Houston,TX,29.76,-95.37,4713325,2020,2,22,0.000262,-0.002388,99.7612
57,5,Phoenix,AZ,33.45,-112.07,4485414,2020,2,22,-0.010700,-0.00782,99.218
71,6,San Diego,CA,32.72,-117.16,3338330,2020,2,22,-0.011200,-0.01768,98.232
85,7,Dallas,TX,32.78,-96.80,2635516,2020,2,22,0.003350,0.00816,100.816
99,8,Las Vegas,NV,36.17,-115.14,2266715,2020,2,22,-0.004770,-0.01034,98.966
113,9,Seattle,WA,47.61,-122.33,2252782,2020,2,22,0.064000,0.06977,106.977
127,10,Fort Worth,TX,32.76,-97.33,2102515,2020,2,22,0.001630,0.00476,100.476
141,11,San Antonio,TX,29.42,-98.49,2003554,2020,2,22,-0.016500,-0.0117,98.83
155,12,San Jose,CA,37.34,-121.89,1927852,2020,2,22,-0.018100,-0.0333,96.67
169,13,Detroit,MI,42.33,-83.05,1749343,2020,2,22,-0.021100,-0.0053,99.47
183,14,Philadelphia,PA,39.95,-75.17,1584064,2020,2,22,0.012900,0.0024,100.24
197,15,Columbus,OH,39.96,-83.00,1316756,2020,2,22,0.011300,0.01438,101.438
211,16,Austin,TX,30.27,-97.74,1273954,2020,2,22,0.008160,0.02106,102.106
225,17,Charlotte,NC,35.23,-80.84,1110356,2020,2,22,-0.012000,-0.01085,98.915
239,18,Indianapolis,IN,39.77,-86.16,964582,2020,2,22,-0.021400,-0.01823,98.177
253,19,Jacksonville,FL,30.33,-81.66,957755,2020,2,22,0.000073,0.001843,100.184
267,20,Memphis,TN,35.15,-90.05,937166,2020,2,22,0.031500,0.033,103.3
281,21,San Francisco,CA,37.77,-122.42,881549,2020,2,22,-0.007350,-0.01389,98.611
295,22,El Paso,TX,31.78,-106.44,839238,2020,2,22,0.022500,0.0074,100.74
309,23,Baltimore,MD,39.29,-76.61,593490,2020,2,22,0.045500,0.04155,104.155
323,24,Portland,OR,45.52,-122.68,812855,2020,2,22,-0.007560,-0.01071,98.929
337,25,Boston,MA,42.36,-71.06,803907,2020,2,22,-0.024400,-0.02641,97.359
351,26,Oklahoma City,OK,35.47,-97.52,797434,2020,2,22,0.032900,0.0432,104.32
365,27,Louisville,KY,38.25,-85.76,766757,2020,2,22,-0.010400,-0.00173,99.827
379,28,Denver,CO,39.74,-104.99,727211,2020,2,22,0.004560,0.00708,100.708
393,29,Washington,DC,38.91,-77.04,705749,2020,2,22,0.031300,0.009,100.9
407,30,Nashville,TN,36.16,-86.78,694144,2020,2,22,-0.011100,-0.01491,98.509
421,31,Milwaukee,WI,43.04,-87.91,945726,2020,2,22,-0.048200,-0.0077,99.23
435,32,Albuquerque,NM,35.09,-106.61,679121,2020,2,22,0.003480,0.00537,100.537
449,33,Tucson,AZ,32.22,-110.93,1047279,2020,2,22,0.022200,0.01242,101.242
463,34,Fresno,CA,36.75,-119.77,999101,2020,2,22,0.001750,0.001407,100.141
477,35,Sacramento,CA,38.58,-121.49,1552058,2020,2,22,0.002570,0.00531,100.531
491,36,Atlanta,GA,33.75,-84.39,1063937,2020,2,22,-0.009440,-0.00147,99.853
505,37,Kansas City,MO,39.10,-94.58,703011,2020,2,22,0.013500,0.0409,104.09
519,38,Miami,FL,25.76,-80.19,2716940,2020,2,22,-0.001090,0.0005,100.05
533,39,Raleigh,NC,35.78,-78.64,1111761,2020,2,22,-0.033400,-0.02943,97.057
547,40,Omaha,NE,41.25,-96.00,571327,2020,2,22,0.051000,0.0643,106.43
559,41,Oakland,CA,37.80,-122.27,1671329,2020,2,22,-0.002020,-0.00599,99.401
573,42,Minneapolis,MN,44.98,-93.27,1265843,2020,2,22,0.019900,0.0534,105.34
587,43,Tampa,FL,27.95,-82.46,1471968,2020,2,22,-0.027400,-0.03443,96.557
601,44,New Orleans,LA,29.95,-90.07,390144,2020,2,22,-0.000127,-0.013127,98.6873
615,45,Wichita,KS,37.69,-97.34,516042,2020,2,22,0.002910,-0.00261,99.739
629,46,Cleveland,OH,41.50,-81.69,1235072,2020,2,22,-0.005500,-0.00136,99.864
643,47,Bakersfield,CA,35.37,-119.02,900202,2020,2,22,-0.002370,-0.01577,98.423
657,48,Honolulu,HI,21.31,-157.86,974563,2020,2,22,-0.011300,-0.00669,99.331
671,49,Boise,ID,43.62,-116.20,481587,2020,2,22,-0.009040,0.00236,100.236
683,50,Salt Lake City,UT,40.76,-111.89,1160437,2020,2,22,-0.014800,-0.0048,99.52
697,51,Virginia Beach,VA,36.85,-75.98,449974,2020,2,22,-0.009930,0.00087,100.087
711,52,Colorado Springs,CO,38.83,-104.82,720403,2020,2,22,-0.040100,-0.0658,93.42
725,53,Tulsa,OK,36.15,-95.99,651552,2020,2,22,-0.003630,0.00104,100.104

In [73]:
# Possible to do a zoom label, satellite image, get negative and posititve value in a single map.
#head_1_df = month_merge_df_reset[month_merge_df_reset["month"]==1]
location = heat_1_df[["lat","lon"]].astype(float)
merchant = heat_1_df["Difference plus 1"].astype(float)

In [74]:
month_2= heat_1_df["Difference plus 1"].max()

In [ ]:

fig = gmaps.figure()


month_2_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_2_map)
fig

In [ ]:
g = [
    'rgba(255, 0, 0, 0)',
    'rgba(255, 255, 0, 1)',
    'rgba(0, 255, 0, 1)',
    'rgba(173, 255, 47, 1)',
    'rgba(152, 251, 152, 1)',
    'rgba(152, 251, 152, 1)',
    'rgba(0, 0, 238, 1)',
    'rgba(186, 85, 211, 1)',
    'rgba(255, 0, 255, 1)',
    'rgba(255, 0, 0, 1)'

]
,gradient= g

In [ ]:
heat_2_df = month_merge_df_reset[(month_merge_df_reset["month"]==3)&(month_merge_df_reset["year"]==2020)]
heat_2_df

In [ ]:
location = heat_2_df[["lat","lon"]].astype(float)
merchant = heat_2_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_3_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_3_map)
fig

In [ ]:
heat_3_df = month_merge_df_reset[(month_merge_df_reset["month"]==4)&(month_merge_df_reset["year"]==2020)]
heat_3_df

In [ ]:
location = heat_3_df[["lat","lon"]].astype(float)
merchant = heat_3_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_4_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_4_map)
fig

In [ ]:
heat_4_df = month_merge_df_reset[(month_merge_df_reset["month"]==5)&(month_merge_df_reset["year"]==2020)]
heat_4_df

In [ ]:
location = heat_4_df[["lat","lon"]].astype(float)
merchant = heat_4_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_5_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_5_map)
fig

In [ ]:
heat_5_df = month_merge_df_reset[(month_merge_df_reset["month"]==6)&(month_merge_df_reset["year"]==2020)]
heat_5_df

In [ ]:
location = heat_5_df[["lat","lon"]].astype(float)
merchant = heat_5_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_6_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_6_map)
fig

In [ ]:
heat_6_df = month_merge_df_reset[(month_merge_df_reset["month"]==7)&(month_merge_df_reset["year"]==2020)]
heat_6_df

In [ ]:
location = heat_6_df[["lat","lon"]].astype(float)
merchant = heat_6_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_7_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_7_map)
fig

In [ ]:
heat_7_df = month_merge_df_reset[(month_merge_df_reset["month"]==8)&(month_merge_df_reset["year"]==2020)]
heat_7_df

In [ ]:
location = heat_7_df[["lat","lon"]].astype(float)
merchant = heat_7_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_8_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_8_map)
fig

In [ ]:
heat_8_df = month_merge_df_reset[(month_merge_df_reset["month"]==9)&(month_merge_df_reset["year"]==2020)]
heat_8_df

In [ ]:
location = heat_8_df[["lat","lon"]].astype(float)
merchant = heat_8_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_9_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_9_map)
fig

In [ ]:
heat_9_df = month_merge_df_reset[(month_merge_df_reset["month"]==10)&(month_merge_df_reset["year"]==2020)]
heat_9_df

In [ ]:
location = heat_9_df[["lat","lon"]].astype(float)
merchant = heat_9_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_10_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_10_map)
fig

In [ ]:
heat_10_df = month_merge_df_reset[(month_merge_df_reset["month"]==11)&(month_merge_df_reset["year"]==2020)]
heat_10_df

In [ ]:
location = heat_10_df[["lat","lon"]].astype(float)
merchant = heat_10_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_11_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_11_map)
fig

In [ ]:
heat_11_df = month_merge_df_reset[(month_merge_df_reset["month"]==12)&(month_merge_df_reset["year"]==2020)]
heat_11_df

In [ ]:
location = heat_11_df[["lat","lon"]].astype(float)
merchant = heat_11_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_12_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_12_map)
fig

In [ ]:
heat_12_df = month_merge_df_reset[(month_merge_df_reset["month"]==1)&(month_merge_df_reset["year"]==2021)]
heat_12_df

In [ ]:
location = heat_12_df[["lat","lon"]].astype(float)
merchant = heat_12_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_01_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_01_map)
fig

In [ ]:
heat_13_df = month_merge_df_reset[(month_merge_df_reset["month"]==2)&(month_merge_df_reset["year"]==2021)]
heat_13_df

In [ ]:
location = heat_13_df[["lat","lon"]].astype(float)
merchant = heat_13_df["Difference plus 1"].astype(float)

In [ ]:
fig = gmaps.figure()


month_02_map = gmaps.heatmap_layer(location,weights=merchant,
                                dissipating=False,max_intensity=diff_max,
                                point_radius=1)



#heat_layer.gradient= ["blue","green","red"]
fig.add_layer(month_02_map)
fig